### ISSUE TITLE
SSTable row keys/values as []byte are uncertain

### ISSUE THREAD

**Issue by GlaDos28** [thomasjungblut/go-sstables#3]
_This is more a suggestion rather than issue._ When working with SSTables, for instance, for Cassandra, it have its format of how to store keys and column values in SSTable. This library's interface only provide writing plain []byte as key and value. More than that, all examples with SSTables (at least which I saw) contains very simple keys and values, such as one-column numbers.

I can understand that SSTable, perhaps, more universal format, than special concrete case for Cassandra, but it will be nice to to some syntactic sugar (API) for writing rows as list of columns with some columns as keys. Cassandra is the primary target for using SSTable, I guess.

More than that, some Cassandra key/value examples should be written, either with new API or at least with plain []byte, with demonstration of how to use it in practice.

**Comment by thomasjungblut** [comment]
hey @GlaDos28, thanks for the suggestion - love it. 

Indeed, as you figured out there is an abstraction on top of the sstables missing. Your row insertion example is necessary for a database (or DBMS) for sure, underneath the columns might actually be stored in separate sstables in a columnar format.
Originally I wanted to add exactly that simple database abstraction into [ncdb](https://github.com/thomasjungblut/ncdb) and I have something stashed locally in my git repo already. I was never super happy about it and its performance, so I didn't even bother to publish it. 

I can maybe pick this up again over the easter holidays, what would be your usecase for this, if I may ask? 

BTW, I haven't actually written this with Cassandra in mind at all, it's actually closer to what HBase does :)

**Comment by GlaDos28** [comment]
@thomasjungblut, thaks for replying so fast :) My usecase is somewhat a bit overcomplicated here, but I can simplify and synthesize an example that will be sufficient for me.

Let's say we have Cassandra table like this:

```
СREATE TABLE example_table (
  cell int,
  lac int,
  dt timestamp,
  isdn bigint,
  imsi bigint,
  imei bigint,
  extra text
  PRIMARY KEY ((cell, lac), dt, isdn, imsi, imei);
```

I want to insert rows into this table as fast as I can. Suppose we use bulk load with writing and then importing SSTable. So ideally, I want something like this:
```golang
...

writer.SetColumns([]string{cell, lac, dt, isdn, imsi, imei, extra})
writer.SetKeyColumns([]string{cell, lac})

// Slice of rows; every row is slice of columns ordered as in schema
var rows [][]interface{}
...

for _, cols := range rows {
    writer.WriteNext(cols)
}

...
```

So this is similar to how familiar SQL drivers write rows with batch inserts and etc, passing rows as list of list of columns.
__________________________
I am in development phase, so I do not know whether this library suits the needs to work with Cassandra. There may be too many incompatibilities with the current implementation, so generalization and adjustment of this library for Cassandra may take too many resources. I rely on the next definition of Cassandra SSTable format:

http://distributeddatastore.blogspot.com/2013/08/cassandra-sstable-storage-format.html

I may participate in upgrading this library to accommodate my needs, but only if I understand that it will be not too difficult comparing to write something of my own concretely for my case without any generalizations. Moreover, I really badly sort out entrails of Cassandra SSTable and this library, so it would take considerable time to dive into, but it is possible.

What do You think about resources needed to adjust the library to be compatible with Cassandra, up to real testing and verifying it is ok? For now I want just to plan what to do, not immediately start doing something in 'with agony' :)

P.S. I thought that HBase is using somewhat called `HTable`. I did not dive into it, perhaps inside it is a lot similar to what SSTable is, but I do not know. Did You test it on HBase bulk load? I'm really interested in this, too, because HBase bulk loading is an equally important task for me, and I would say, deals with HBase are much worse than with Cassandra, in terms of suitable libraries and etc. :)

**Comment by GlaDos28** [comment]
Well, thanks for the information, including links! I'll take a tour. So, I guess I will continue on my own now. I see that this library is great, but not suitable for the cases I need.

Thanks for everything, good luck further!
