### ISSUE TITLE
Install v2 problem

### ISSUE THREAD

**Issue by sebheitzmann** [thomasjungblut/go-sstables#32]
Hi, 

i'm interessed by your library for a spécific use case. But i can't install the v2 version.

I have tried with different go version ( 1.21, 1.22, 1.23 ) without success. Can't understand what's going on. 

```
go get github.com/thomasjungblut/go-sstables@v2
go: github.com/thomasjungblut/go-sstables@v2: no matching versions for query "v2"
``` 

Thanks in advance.

**Comment by thomasjungblut** [comment]
Hey @sebheitzmann - terribly sorry for the late reply.

Thanks for reporting, I've certainly messed up the go mod here as the major version releases need to be defined differently as documented in https://go.dev/blog/v2-go-modules

I think I'm going to kick the v2 release out of the repo for now and will re-release the v2 as v1.4.0 and the current main as v1.5.0. Give me a few minutes, brb.

**Comment by thomasjungblut** [comment]
Done. 

> go get github.com/thomasjungblut/go-sstables

should get you the v1.5.0. Alternatively you can get the v1.4.0 which was the v2 release you've tried to pull earlier.
Note I found a failure path in #31 in the sstables, which is a bit nasty to repair after it happend. May or may not apply to you when you're using this.

Thanks!

**Comment by sebheitzmann** [comment]
Thank you very much. I will give it a try tomorrow

**Comment by sebheitzmann** [comment]
It works, thank you very much. I will close this issue.

Juste one question. It seems that there is no garbage collection implemented to effectively remove the thumbstoned keys. I am wrong ? If not i can maybe contribute to implement it.

**Comment by thomasjungblut** [comment]
Lovely, thanks for confirming. 

The tombstoning GC is missing, that's right. Long-standing TODO here: https://github.com/thomasjungblut/go-sstables/blob/242f3324db96b2cb43539173fb6eade97a793718/simpledb/compaction.go#L118-L122

Shouldn't be super difficult to add a more sophisticated version of [the reduce function](https://github.com/thomasjungblut/go-sstables/blob/main/sstables/super_sstable_reader.go#L101-L113). If you want to contribute it, please do - happy to help you.

**Comment by sebheitzmann** [comment]
PR created
