### ISSUE TITLE
compaction generate a memory leak ?

### ISSUE THREAD

**Issue by sebheitzmann** [thomasjungblut/go-sstables#37]
I think that the compaction process has a memory leak.
![image](https://github.com/user-attachments/assets/17583f66-2f23-4eef-b8ca-b43cf273f63f)

I will try to figure out why.

**Comment by sebheitzmann** [comment]
It's the same problem without compaction ... To be continued

**Comment by thomasjungblut** [comment]
Thanks for checking! I assume it's the behavior of the super sstable and its memory mapped file. You can run a memprofile and see where all the memory goes :)

**Comment by sebheitzmann** [comment]
The step up is from the memstore flush, not the compaction. I continue to find out why. Pprof don't give me usefull information.

**Comment by thomasjungblut** [comment]
I assume, because of the async flushing from the channel, the memory temporarily increases. If you can't write fast enough, the memory will fill up quickly again with a second memstore, which makes the apparence that it doubles.
 
The second memstore flush is then waiting for the channel to free again, so this is proving some backpressure in this situation

**Comment by sebheitzmann** [comment]
![image](https://github.com/user-attachments/assets/e9617d07-60ea-446f-9e4c-b104a021fe54)

The big step is the flush. And I stop all action on the database. The memory should drop back to the previous memory usage after the flush.

**Comment by sebheitzmann** [comment]
maybe, i'm investigating. This pool should be released after the close.

**Comment by sebheitzmann** [comment]
https://github.com/libp2p/go-buffer-pool/issues/35

**Comment by thomasjungblut** [comment]
Yeah, the GC behavior depends a lot on the memory pressure of the machine. There's a great blog post that highlights this:
https://tip.golang.org/doc/gc-guide

**Comment by sebheitzmann** [comment]
The GC has very strange behavior sometime ... Hard to understand sometime. The memory stabilize after some time. So maybe no memory leak in this code.
