### ISSUE TITLE
Checksum mismatch on loading

### ISSUE THREAD

**Issue by sebheitzmann** [thomasjungblut/go-sstables#38]
I got some error like this : 

error in sstable '44/sstable_000000000000001/' while hashing value at offset [505843]: Checksum mismatch: expected 29cbe412906044a5, got 556cce18f87966a7

I can't really understand why it is produced. How can we produce wrong checksum ?

Could it be linked to #31 ?

Any advice ?

**Comment by thomasjungblut** [comment]
Could be, did you receive any error while writing? Any specific position that may cause this problem? Is it the last record in the file? 

It might also happen when the key sstable contains wrong offsets, so the records are split, which is similar to #31

**Comment by sebheitzmann** [comment]
Yes, the checksum error is on the last key. No errors on writting.

**Comment by sebheitzmann** [comment]
maybe my fault, i'm still inverstigate

**Comment by thomasjungblut** [comment]
did you close the sstable at the end? maybe the buffer hasn't been flushed entirely

**Comment by sebheitzmann** [comment]
After a little more investigate it seem that the problem was with a buffer in the calling code. I Close this issue.
