### ISSUE TITLE
Thread safe?

### ISSUE THREAD

**Issue by asad-awadia** [thomasjungblut/go-sstables#4]
Is the code in here threadsafe?

**Comment by thomasjungblut** [comment]
Hey!

It's not, you would have to wrap every read and write with a mutex. There
is a bunch of offset handling and state involved.

Best,
Thomas

**Comment by asad-awadia** [comment]
Got it!

Thank you for building this - Great work here!

**Comment by asad-awadia** [comment]
@thomasjungblut one more thing - the merge reads the entire ss table into memory in a priority queue - would that not cause memory bloating/out of memory issues?

**Comment by thomasjungblut** [comment]
I can't check this right now, but it should only read the next element of
each sstable in the merge into memory. So only O(n) memory use where n is
the number of sstables you want to merge.

**Comment by asad-awadia** [comment]
Yes you are correct - Just checked

@thomasjungblut mm flush keeps overwriting the sstables on disk? It doesn't create a new table?

**Comment by thomasjungblut** [comment]
Flush should only sychronize to disk, so flush the disk buffer. I believe
the related syscall would be fsync.
